/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import control.MuaControl;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MuaModel;

/**
 *
 * @author Admin
 */
public class Mua extends javax.swing.JFrame {
  ////////////
    MuaControl muaControl = new MuaControl();
    private int flagMaDat;
    /**
     * Creates new form Mua
     */
    public Mua() throws SQLException {
        initComponents();
         loadTableDaMua();
        loadTableMua();
    }
    private void loadTableMua() throws SQLException {

        DefaultTableModel mua = (DefaultTableModel) jTableMua.getModel();

        mua.setRowCount(0);

        for (MuaModel muaModel : muaControl.GetTableMua()) {
            Object[] obj = {muaModel.getMaDat(), muaModel.getTenDat(), muaModel.getDienTich(), muaModel.getGiaDat(), muaModel.getViTri(), muaModel.getViTri()};
            mua.addRow(obj);
        }
    }
    private void loadTableDaMua() throws SQLException {

        DefaultTableModel daMua = (DefaultTableModel) jTableDaMua.getModel();
        daMua.setRowCount(0);

        for (MuaModel item : muaControl.GetTableDaMua()) {
            Object[] obj = {item.getMaDat(), item.getTenDat(), item.getDienTich(), item.getGiaDat(), item.getViTri(), item.getViTri()};
            daMua.addRow(obj);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMua = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMua = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButtonHuyMua = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDaMua = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonMua.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonMua.setForeground(new java.awt.Color(0, 204, 0));
        jButtonMua.setText("MUA");
        jButtonMua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMuaActionPerformed(evt);
            }
        });

        jTableMua.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableMua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableMua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Đất", "Tên Đất", "Diện Tích (m2)", "Giá Đất ($)", "Vị Trí"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMua.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableMua.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableMua.setGridColor(new java.awt.Color(255, 255, 255));
        jTableMua.setRowHeight(30);
        jTableMua.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jTableMua.setShowGrid(true);
        jTableMua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMuaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableMua);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Danh Sách Đất Đang Được Bán");

        jButtonHuyMua.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonHuyMua.setForeground(new java.awt.Color(255, 102, 102));
        jButtonHuyMua.setText("HUỶ MUA");
        jButtonHuyMua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyMuaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Danh Sách Đất Bạn Đang Mua");

        jTableDaMua.setBorder(new javax.swing.border.MatteBorder(null));
        jTableDaMua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTableDaMua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Đất", "Tên Đất", "Diện Tích (m2)", "Giá Đất ($)", "Vị Trí"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDaMua.setRowHeight(50);
        jTableDaMua.setRowMargin(10);
        jTableDaMua.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jTableDaMua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDaMuaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableDaMua);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MUA ĐẤT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1077, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(351, 351, 351))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonHuyMua, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(61, 61, 61)
                                    .addComponent(jButtonMua, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(35, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonMua, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(33, 33, 33)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonHuyMua, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMuaActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Bạn muốn mua lô đất này?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            try {
                if (muaControl.UpdateMua(flagMaDat, "Da Ban") == true) {
                    JOptionPane.showConfirmDialog(this, "Mua Thành Công!", "", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    muaControl.ThemDaMua(flagMaDat);
                }
            } catch (SQLException ex) {
                JOptionPane.showConfirmDialog(this, "Lỗi Mua!", "", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
            }
        }
        //
        try {
            loadTableMua();
            loadTableDaMua();
        } catch (SQLException ex) {
            Logger.getLogger(Mua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonMuaActionPerformed

    private void jTableMuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMuaMouseClicked
        // TODO add your handling code here:
        int x = jTableMua.getSelectedRow();
        MuaModel muaModel = muaControl.GetMuaByIndex(x);

        flagMaDat = muaModel.getMaDat();
    }//GEN-LAST:event_jTableMuaMouseClicked

    private void jButtonHuyMuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyMuaActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Bạn muốn huỷ mua lô đất này?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            try {
                if (muaControl.UpdateMua(flagMaDat, "Chua Ban") == true && muaControl.XoaDaMua(flagMaDat) == true) {
                    JOptionPane.showConfirmDialog(this, "Huỷ Mua Thành Công!", "", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showConfirmDialog(this, "Lỗi Huỷ Mua!", "", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
            }
        }
        try {
            loadTableDaMua();
            loadTableMua();
        } catch (SQLException ex) {
            Logger.getLogger(Mua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonHuyMuaActionPerformed

    private void jTableDaMuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDaMuaMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        int x = jTableDaMua.getSelectedRow();
        MuaModel muaModel = muaControl.GetDaMuaByIndex(x);

        flagMaDat = muaModel.getMaDat();
    }//GEN-LAST:event_jTableDaMuaMouseClicked
private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {                                               
        try {
            // TODO add your handling code here:
            loadTableDaMua();
            loadTableMua();
        } catch (SQLException ex) {
            Logger.getLogger(Mua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                     
    /**
//     * @param args the command line arguments
     */
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      //  java.awt.EventQueue.invokeLater(new Runnable() {
        //    public void run() {
          //      new Mua().setVisible(true);
          //  }
     //   });
  //  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHuyMua;
    private javax.swing.JButton jButtonMua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableDaMua;
    private javax.swing.JTable jTableMua;
    // End of variables declaration//GEN-END:variables

 
}
