/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.UserControl;
import control.MuaControl;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Dat;

/**
 *
 * @author NGUYỄN VĂN LINH 22211TT0127
 */
public class FrMua extends javax.swing.JFrame {

    MuaControl muaControl = new MuaControl();
    private int flagMaDatMua;
    private int flagMaDatDaMua;

    public FrMua() throws SQLException {
        initComponents();
        loadTableDaMua();
        loadTableMua();
    }

    private void loadTableMua() throws SQLException {

        DefaultTableModel mua = (DefaultTableModel) jTableMua.getModel();
        mua.setRowCount(0);

        for (Dat muaModel : muaControl.GetTableMua()) {
            Object[] obj = {muaModel.getMaDat(), muaModel.getTenDat(), muaModel.getDienTich(), muaModel.getGiaDat(), muaModel.getViTri(), muaModel.getTrangThai()};
            mua.addRow(obj);
        }
    }

    private void loadTableDaMua() throws SQLException {

        DefaultTableModel daMua = (DefaultTableModel) jTableDaMua.getModel();
        daMua.setRowCount(0);

        for (Dat item : muaControl.GetTableDaMua()) {
            Object[] obj = {item.getMaDat(), item.getTenDat(), item.getDienTich(), item.getGiaDat(), item.getViTri(), item.getTrangThai()};
            daMua.addRow(obj);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jButtonMua = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMua = new javax.swing.JTable();
        jButtonThoat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonHuyMua = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDaMua = new javax.swing.JTable();
        jButtonRefresh = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MUA ĐẤT");

        jButtonMua.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonMua.setForeground(new java.awt.Color(0, 204, 0));
        jButtonMua.setText("MUA");
        jButtonMua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMuaActionPerformed(evt);
            }
        });

        jTableMua.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableMua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableMua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Đất", "Tên Đất", "Diện Tích (m2)", "Giá Đất ($)", "Vị Trí"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMua.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableMua.setGridColor(new java.awt.Color(255, 255, 255));
        jTableMua.setRowHeight(30);
        jTableMua.setRowMargin(5);
        jTableMua.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jTableMua.setShowGrid(true);
        jTableMua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMuaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableMua);

        jButtonThoat.setBackground(new java.awt.Color(255, 0, 0));
        jButtonThoat.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonThoat.setForeground(new java.awt.Color(255, 255, 255));
        jButtonThoat.setText("EXIT");
        jButtonThoat.setBorder(null);
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Shop: Danh Sách Đất Đang Được Bán");

        jButtonHuyMua.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonHuyMua.setForeground(new java.awt.Color(255, 102, 102));
        jButtonHuyMua.setText("HUỶ MUA");
        jButtonHuyMua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyMuaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Giỏ Hàng: Danh Sách Đất Bạn Đang Mua");

        jTableDaMua.setBorder(new javax.swing.border.MatteBorder(null));
        jTableDaMua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTableDaMua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Đất", "Tên Đất", "Diện Tích (m2)", "Giá Đất ($)", "Vị Trí"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDaMua.setRowHeight(50);
        jTableDaMua.setRowMargin(10);
        jTableDaMua.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jTableDaMua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDaMuaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableDaMua);

        jButtonRefresh.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonRefresh.setForeground(new java.awt.Color(204, 204, 0));
        jButtonRefresh.setText("LÀM MỚI");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jMenuBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenu3.setText("Menu");

        jMenuItem2.setText("Bán Đất");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Quản Trị");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonRefresh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jButtonMua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jButtonHuyMua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMua, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(111, 111, 111)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonHuyMua, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonThoat))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Click jTableMua, lấy vị trí x truyền vào GetMuaByIndex để lấy ra đối tượng.
    //Lưu maDat của đối tượng vào flagMaDatMua
    private void jTableMuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMuaMouseClicked
        // TODO add your handling code here:
        int x = jTableMua.getSelectedRow();
        Dat dat = muaControl.GetMuaByIndex(x);

        //Lưu maDat của đối tượng, dùng nó để truy vấn đến đối tượng trong danh sách ArrayList
        flagMaDatMua = dat.getMaDat();
    }//GEN-LAST:event_jTableMuaMouseClicked

// Click chọn, lưu flagMaDat
// Nhấn button FrMua, update dl cho đối tượng có maDat = flagMaDat thành "Da Ban" 
    private void jButtonMuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMuaActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Bạn muốn mua lô đất này?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            try {
                muaControl.UpdateCSDL(flagMaDatMua, "Da Ban");
                JOptionPane.showConfirmDialog(this, "Mua Thành Công!", "", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
                muaControl.ThemDatDaMua(flagMaDatMua);
                
            } catch (SQLException ex) {
                JOptionPane.showConfirmDialog(this, "Lỗi Mua!", "", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
            }
        }
        
        // Làm mới table:
        try {
            loadTableMua();
            loadTableDaMua();
        } catch (SQLException ex) {
            Logger.getLogger(FrMua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonMuaActionPerformed
//Nhấn EXIT, đóng Frame hiện tại và mở Frame được chỉ định 'FrHome'
    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FrHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonThoatActionPerformed

    //Nhấn Huy FrMua, update dl cho đối tượng có maDat = flagMaDat thành "Da Ban" 
    private void jButtonHuyMuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyMuaActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Bạn muốn huỷ mua lô đất này?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            try {
                muaControl.UpdateCSDL(flagMaDatDaMua, "Chua Ban");
                muaControl.XoaDatDaMua(flagMaDatDaMua);
                JOptionPane.showConfirmDialog(this, "Huỷ Mua Thành Công!", "", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showConfirmDialog(this, "Lỗi Huỷ Mua!", "", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
            }
        }

        // Làm mới table
        try {
            loadTableDaMua();
            loadTableMua();
        } catch (SQLException ex) {
            Logger.getLogger(FrMua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonHuyMuaActionPerformed

    //Click jTableDaMua, lưu maDat của đối tượng vào flagMaDatDaMua
    private void jTableDaMuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDaMuaMouseClicked
        // TODO add your handling code here:
        int x = jTableDaMua.getSelectedRow();
        Dat daMuaModel = muaControl.GetDaDaMuaByIndex(x);
        flagMaDatDaMua = daMuaModel.getMaDat();
    }//GEN-LAST:event_jTableDaMuaMouseClicked

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        try {
            // TODO add your handling code here:
            loadTableDaMua();
            loadTableMua();
        } catch (SQLException ex) {
            Logger.getLogger(FrMua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FrBan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if (UserControl.getFlagID() == 1) {
            this.setVisible(false);
            try {
                new FrQuanTri().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(FrHome.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        } else {
            JOptionPane.showConfirmDialog(this, "Bạn Không phải Admin", "", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItem3ActionPerformed
/////////

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrMua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrMua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrMua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrMua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrMua().setVisible(true);
//            }
//        });
//}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonHuyMua;
    private javax.swing.JButton jButtonMua;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableDaMua;
    private javax.swing.JTable jTableMua;
    // End of variables declaration//GEN-END:variables
}
